"use client";
import { useEffect, useState } from "react";
import type { Signup } from "../../lib/organizer";
type Configuration={pinConfigured:boolean;deliveryConfigured:boolean};
export default function NoticeDashboard({initialRows,initialPage,total}:{initialRows:Signup[];initialPage:number;total:number}) {
  const [rows,setRows]=useState(initialRows),[page,setPage]=useState(initialPage),[loading,setLoading]=useState(false);
  const [selected,setSelected]=useState<Record<string,Signup>>({}),[pin,setPin]=useState(""),[unlocked,setUnlocked]=useState(false);
  const [config,setConfig]=useState<Configuration|null>(null),[subject,setSubject]=useState(""),[message,setMessage]=useState("");
  const [review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState("");
  const [requestId,setRequestId]=useState(""),[attempted,setAttempted]=useState(false),[firstAttempt,setFirstAttempt]=useState(0);
  useEffect(()=>{fetch("/api/organizer/notices",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();setConfig(await r.json());}).catch(()=>setError("Mailer configuration is temporarily unavailable."));},[]);
  const participants=Object.values(selected);const emailCount=new Set(participants.map(p=>p.email.toLowerCase())).size;
  const allPageSelected=rows.length>0&&rows.every(row=>!!selected[row.id]);
  function select(row:Signup,checked:boolean){setSelected(previous=>{const next={...previous};if(checked){if(Object.keys(next).length>=500)return next;next[row.id]=row;}else delete next[row.id];return next;});setReview(false);setResult("");}
  async function load(nextPage:number){setLoading(true);setError("");try{const r=await fetch(`/api/organizer/entries?page=${nextPage}`,{cache:"no-store"});const d=await r.json() as {error?:string;rows:Signup[];page:number;deliveryConfigured:boolean;accepted:number};if(!r.ok)throw new Error(d.error||"The notice service is unavailable.");setRows(d.rows);setPage(d.page);}catch(e){setError(e instanceof Error?e.message:"Could not load registrations.");}finally{setLoading(false);}}
  async function unlock(){setBusy(true);setError("");try{const r=await fetch("/api/organizer/notices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"unlock",pin})});const d=await r.json() as {error?:string;rows:Signup[];page:number;deliveryConfigured:boolean;accepted:number};if(!r.ok)throw new Error(d.error||"The notice service is unavailable.");setUnlocked(true);setConfig({pinConfigured:true,deliveryConfigured:d.deliveryConfigured});}catch(e){setError(e instanceof Error?e.message:"Could not unlock the mailer.");}finally{setBusy(false);}}
  async function send(){if(firstAttempt&&Date.now()-firstAttempt>=86400000){setError("The safe retry window has expired. Check delivery in Resend before preparing another notice.");return;}if(!firstAttempt)setFirstAttempt(Date.now());setBusy(true);setError("");setAttempted(true);const id=requestId||crypto.randomUUID();setRequestId(id);try{const r=await fetch("/api/organizer/notices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"send",pin,requestId:id,recipientIds:participants.map(p=>p.id),subject,message})});const d=await r.json() as {error?:string;rows:Signup[];page:number;deliveryConfigured:boolean;accepted:number};if(!r.ok)throw new Error(d.error||"The notice service is unavailable.");setResult(`${d.accepted} ${d.accepted===1?"notice was":"notices were"} accepted by the email service. Delivery to inboxes can take a moment.`);setSelected({});setSubject("");setMessage("");setReview(false);setRequestId("");setAttempted(false);setFirstAttempt(0);}catch(e){setError(e instanceof Error?e.message:"Sending could not be confirmed. Retry this same notice.");}finally{setBusy(false);}}
  const selectionLocked=busy||attempted;
  return <>
    <div className="notice-selection"><strong>{participants.length} selected</strong><span>Select signup entries to receive an event notice.</span><button type="button" className="notice-small-button" disabled={!participants.length||selectionLocked} onClick={()=>{setSelected({});setReview(false);}}>Clear selection</button></div>
    <div className="table-wrap"><table><caption className="sr-only">Thriller Flash Mob registrations with notice recipients</caption><thead><tr><th scope="col"><input type="checkbox" aria-label="Select all registrations on this page" checked={allPageSelected} disabled={selectionLocked} onChange={e=>{const checked=e.target.checked;setSelected(previous=>{const next={...previous};rows.forEach(row=>{if(checked&&Object.keys(next).length<500)next[row.id]=row;else if(!checked)delete next[row.id];});return next;});setReview(false);}}/></th><th scope="col">Name</th><th scope="col">Email</th><th scope="col">Phone</th><th scope="col">Signed up</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={`Select ${row.name} for a notice`} checked={!!selected[row.id]} disabled={selectionLocked} onChange={e=>select(row,e.target.checked)}/></td><td>{row.name}</td><td>{row.email}</td><td>{row.phone}</td><td>{new Intl.DateTimeFormat("en-US",{timeZone:"America/Detroit",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(row.created_at.replace(" ","T")+"Z"))}</td></tr>)}</tbody></table></div>
    <nav className="pagination" aria-label="Registration pages"><span>Showing {(page-1)*50+1}–{Math.min(page*50,total)} of {total}</span><div>{page>1&&<button className="notice-page-button" disabled={loading} onClick={()=>void load(page-1)}>Previous</button>}{page*50<total&&<button className="notice-page-button" disabled={loading} onClick={()=>void load(page+1)}>Next</button>}<button className="notice-page-button" disabled={loading} onClick={()=>void load(page)}>Refresh</button></div></nav>
    <section className="notice-mailer" aria-labelledby="notice-heading"><p className="eyebrow">PIN PROTECTED · EVENT NOTICES ONLY</p><h2 id="notice-heading">Keep the mob in the loop.</h2><p>Send practice reminders and event updates to selected registered participants. Each person receives a separate email from noreply@nextdesign.dev.</p>
      {config&&!config.deliveryConfigured&&<p className="notice-setup" role="status">Email delivery setup is pending. Sending is disabled until a sender and email service are connected.</p>}
      {!unlocked?<form className="notice-unlock" onSubmit={e=>{e.preventDefault();void unlock();}}><label htmlFor="mailer-pin">Six-digit mailer PIN</label><input id="mailer-pin" type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete="off" value={pin} onChange={e=>setPin(e.target.value)} disabled={busy||!config?.pinConfigured}/><button disabled={busy||!config?.pinConfigured}>{busy?"Checking PIN…":"Unlock notice mailer"}</button>{config&&!config.pinConfigured&&<small>The organizer must configure the mailer PIN first.</small>}</form>:<>
        <button type="button" className="notice-small-button" disabled={busy||attempted} onClick={()=>{setUnlocked(false);setPin("");setReview(false);}}>Lock mailer</button>
        {!review?<form className="notice-compose" onSubmit={e=>{e.preventDefault();setReview(true);setError("");}}><label htmlFor="notice-subject">Notice subject</label><input id="notice-subject" required minLength={3} maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Practice reminder for Thursday"/><label htmlFor="notice-message">Message</label><textarea id="notice-message" required minLength={10} maxLength={5000} rows={7} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write your event notice…"/><p>{participants.length} selected · {emailCount} unique email {emailCount===1?"address":"addresses"}. Select up to 500 participants; selections stay selected when you change pages.</p><button disabled={!participants.length||busy}>Review notice</button></form>:<div className="notice-review"><h3>Review before sending</h3><p>From: noreply@nextdesign.dev</p><p>To: {emailCount} selected email {emailCount===1?"address":"addresses"}</p><details><summary>View selected recipients</summary><ul>{participants.map(p=><li key={p.id}>{p.name} — {p.email}</li>)}</ul></details><h4>South Haven Thriller — {subject}</h4><div className="notice-preview-message">{message}</div><p className="notice-preview-footer">South Haven Thriller Flash Mob<br/>Event notice for registered participants.<br/>https://tinyurl.com/sohathriller</p><div className="notice-actions"><button disabled={busy||!config?.deliveryConfigured} onClick={()=>void send()}>{busy?"Sending notice…":attempted?"Retry this same notice":`Send notice to ${emailCount}`}</button><button className="notice-small-button" disabled={busy||attempted} onClick={()=>setReview(false)}>Edit notice</button></div>{attempted&&<p>Keep this notice unchanged until sending is confirmed. Retry within 24 hours using the same send reference to prevent duplicates.</p>}</div>}
      </>}
      {error&&<p className="notice-error" role="alert">{error}</p>}{result&&<p className="notice-success" role="status">{result}</p>}
    </section>
  </>;
}
