import { requireChatGPTUser } from "../chatgpt-auth";
import { getOrganizer, signupDatabase, type Signup } from "../../lib/organizer";
import { Download, Moon, Users } from "lucide-react";
export const dynamic="force-dynamic";
export default async function Organizer({searchParams}:{searchParams:Promise<{page?:string}>}){
 await requireChatGPTUser("/organizer");
 const owner=await getOrganizer();
 if(!owner)return <main className="organizer"><a href="/">Back to the event</a><h1>Organizer access only</h1><p>Sign in with the organizer account to view registrations.</p><a href="/signout-with-chatgpt?return_to=%2Forganizer" target="_top">Switch account</a></main>;
 const params=await searchParams;let page=Math.max(1,Math.min(100000,Math.floor(Number(params.page)||1)));
 let rows:Signup[]=[];let total=0;let unavailable=false;
 try{const db=signupDatabase();total=(await db.prepare("SELECT COUNT(*) AS total FROM signups").first<{total:number}>())?.total??0;page=Math.min(page,Math.max(1,Math.ceil(total/50)));rows=(await db.prepare("SELECT id, name, email, phone, created_at FROM signups ORDER BY created_at DESC, id DESC LIMIT 50 OFFSET ?").bind((page-1)*50).all<Signup>()).results;}catch(e){console.error("Organizer dashboard unavailable",e);unavailable=true;}
 return <main className="organizer"><header className="organizer-header"><a className="brand" href="/"><Moon size={23}/><span>SOUTH HAVEN <b>THRILLER FLASH MOB</b></span></a><a href="/">View event page</a></header><div className="organizer-heading"><div><p className="eyebrow">PRIVATE · ORGANIZER ONLY</p><h1>Who’s joining the mob?</h1><p className="organizer-subtitle">Your event registrations, all in one place.</p></div>{!unavailable&&total>0&&<a className="export-button" href="/api/organizer/export"><Download size={19}/> Download CSV</a>}</div>
 {unavailable?<div className="organizer-empty" role="alert"><h2>Registrations are temporarily unavailable</h2><p>Please refresh the page in a moment.</p><a href="/organizer">Try again</a></div>:<><div className="signup-count"><Users size={22}/><strong>{total}</strong><span>{total===1?"participant registered":"participants registered"}</span></div>{total===0?<div className="organizer-empty"><h2>The mob starts here.</h2><p>No registrations yet. New signups will appear here after they’re submitted.</p><a href="/organizer">Refresh registrations</a></div>:<><div className="table-wrap"><table><caption className="sr-only">Thriller Flash Mob registrations</caption><thead><tr><th scope="col">Name</th><th scope="col">Email</th><th scope="col">Phone</th><th scope="col">Signed up</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.email}</td><td>{row.phone}</td><td>{new Intl.DateTimeFormat("en-US",{timeZone:"America/Detroit",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(row.created_at.replace(" ","T")+"Z"))}</td></tr>)}</tbody></table></div><nav className="pagination" aria-label="Registration pages"><span>Showing {(page-1)*50+1}–{Math.min(page*50,total)} of {total}</span><div>{page>1&&<a href={"/organizer?page="+(page-1)}>Previous</a>}{page*50<total&&<a href={"/organizer?page="+(page+1)}>Next</a>}<a href={"/organizer?page="+page}>Refresh</a></div></nav></>}</>}
 <p className="organizer-privacy">Contact details are visible only to the organizer. Signup times are shown in Eastern Time.</p><footer><span>By Next Design</span></footer></main>;
}
