"use client";
import { useState, useEffect } from "react";
import { CalendarDays, MapPin, Music2, Check, Moon } from "lucide-react";
export default function Home(){
 const [status,setStatus]=useState("idle"); const [error,setError]=useState("");
 async function signup(input: {name:string;email:string;phone:string;website?:string}) {setStatus("saving");setError("");try{const r=await fetch("/api/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Please try again.");setStatus("success");return {status:"registered"};}catch(e){setStatus("idle");setError(e instanceof Error?e.message:"Please try again.");throw e;}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:"register_thriller_participant",title:"Join the Thriller Flash Mob",description:"Save a participant signup for the South Haven Thriller Flash Mob.",inputSchema:{type:"object",properties:{name:{type:"string"},email:{type:"string"},phone:{type:"string"}},required:["name","email","phone"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:signup},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 return <main>
 <header className="topbar"><a className="brand" href="#"><Moon size={23}/><span>SOUTH HAVEN <b>AFTER DARK</b></span></a><a className="nav-link" href="#signup">Join the flash mob</a></header>
 <section className="hero"><div className="poster-wrap"><img className="poster" src="/event-poster.jpeg" alt="South Haven Thriller Flash Mob flyer with a full moon and zombie dancers, event October 30 and practices October 8, 15, 22 and 29"/></div>
 <div className="hero-content"><p className="eyebrow"><span/> A COMMUNITY HALLOWEEN EVENT</p><h1>South Haven,<br/>let’s make it<br/><em>THRILLER.</em></h1><p className="intro">A little rhythm. A little zombie. A whole lot of community. Join us for a Thriller flash mob in downtown South Haven.</p><div className="event-meta"><span><CalendarDays size={19}/> Friday, October 30</span><span><MapPin size={19}/> Downtown South Haven</span></div>
 <div className="signup-card" id="signup">{status==="success"?<div className="success" role="status"><div className="check-icon"><Check/></div><h2>You’re in!</h2><p>Your signup has been saved. Come practice with us Thursdays at 5:00 PM at Moose Lodge in South Haven.</p><a href="#practices">See the practice dates</a></div>:<><div className="form-heading"><h2>Join the mob.</h2><span>NO DANCE EXPERIENCE NEEDED</span></div><p>We’ll learn a fun, shortened Thriller routine together.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void signup({name:String(f.get("name")),email:String(f.get("email")),phone:String(f.get("phone")),website:String(f.get("website"))}).catch(()=>{});}}><label htmlFor="name">Full name <span>*</span></label><input id="name" name="name" autoComplete="name" required maxLength={120} placeholder="Your full name"/><div className="field-row"><div><label htmlFor="email">Email address <span>*</span></label><input id="email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></div><div><label htmlFor="phone">Phone number <span>*</span></label><input id="phone" name="phone" type="tel" autoComplete="tel" required maxLength={30} pattern="[+0-9() .-]{7,30}" title="Enter a phone number with at least 7 digits." placeholder="(269) 555-0123"/></div></div><div className="trap" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{error&&<p className="error" role="alert">{error}</p>}<button disabled={status==="saving"}>{status==="saving"?"Saving your spot…":"Count me in"}<Music2 size={20}/></button><p className="form-note">All fields required. Your details are collected for this event.</p></form></>}</div></div></section>
 <section className="practices" id="practices"><div className="practice-title"><p className="eyebrow">LEARN THE MOVES. BRING THE FUN.</p><h2>A few Thursdays.<br/><em>One unforgettable night.</em></h2><p>Practice together, then put on your zombie best and bring Thriller to life downtown.</p></div><div className="practice-details"><div className="practice-info"><CalendarDays size={24}/><div><h3>Thursdays at 5:00 PM</h3><p>Moose Lodge · South Haven</p></div></div><div className="dates">{["08","15","22","29"].map(day=><div className="date" key={day}><span>OCT</span><strong>{day}</strong><small>THURSDAY</small></div>)}</div><p className="drop-in"><Music2 size={18}/> Curious? Just show up Thursday!</p></div></section><footer><span>SOUTH HAVEN THRILLER FLASH MOB</span><p>Let’s bring Thriller to downtown South Haven.</p></footer>
 </main>;
}
